apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: main-application
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: reg.devnoneknow.online/jobseeker/job-seeker-server:6
          ports:
            - containerPort: 8800
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGO_URI
            - name: MONGO_DATABASE
              value: "JobSeeker"
            - name: SIGNER_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SIGNER_KEY
