apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: main-application
stringData:
  MONGO_URI: mongodb://mongodb-svc:27017
  SIGNER_KEY: FPXK0J11FaqfzXu8hHZ7v9VxXfFjV1wVgewNyeTxEF7Mbyj1wFmhZIbIfG6heC9D
