apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: main-application
spec:
  selector:
    app: backend
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
