apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: main-application
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      containers:
        - name: backend
          image: noneknow12/job-seeker-backend:v5
          ports:
            - containerPort: 8800
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGO_URI
            - name: MONGO_DATABASE
              value: "JobSeeker"
            - name: SIGNER_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SIGNER_KEY
