apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: main-application
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/db
