apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: main-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongodb" # Headless service name
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongo-storage
  volumeClaimTemplates:
  - metadata:
      name: mongo-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi # Adjust size as needed
